---
title: "Exercise 1.6"
author: "Oscar Oelrich"
date: "12 december 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Exercise 1.6

Approximately $1/125$ of all births are fraternal twins, and approximately $1/300$ of all births are identical twins. Elvis Presley had a twin brother who died at birth. Given the approximation that half of all births are boys, what is the probability that Elvis had a twin brother?

We will solve the problem using Bayes' theorem. We use the following notation.

* *IT* is the event of an identical twin
* *FT* is the event of a fraternal twin
* *T* denotes the probability of having a twin and is obtained by summing $IT$ and $FT$
* *B* denotes the probability of having a brother


We then have that

$$\begin{equation}
P((IT)|(T,B))=\frac{P(T,B|(IT))P(IT)}{P(T,B)}
\end{equation}$$

where we have that $P(T,B|IT)=1$, since if Elvis has an identical twin, obviously it's a brother, the probability for $IT$ is given and the probability $P(T,B)=P(IT,B)+P(FT,B)=P(IT)+P(B|FT)P(FT)=1/300+1/2 *1/125$ which gives the solution

$$\begin{equation}
P((IT)|(T,B))=\frac{1*\frac{1}{300}}{\frac{1}{300}+\frac{1}{2}\frac{1}{125}}=\frac{5}{11}
\end{equation}$$

